In [6]:
import pandas as pd
from pathlib import Path
from testgen.analysis_utils import *

In [7]:
labels = get_sensors_labels()
labels

array(['Acc', 'WSA', 'WS', 'YR', 'ST'], dtype='<U3')

In [8]:
# read results file
base_path = Path().cwd()
results_path = base_path.parent / "results"
    
available_results = get_best_results(results_path, "single_gpt*.json")

available_results

[PosixPath('/mnt/d/scripts/hil/hil-test-case-gen/results/single_gpt-4o-mini_n-1_acc-0.934_10.31.2024-14:30:19.json'),
 PosixPath('/mnt/d/scripts/hil/hil-test-case-gen/results/single_gpt-4o-mini_n-3_acc-0.905_11.04.2024-13:06:59.json'),
 PosixPath('/mnt/d/scripts/hil/hil-test-case-gen/results/single_gpt-4o-mini_n-5_acc-0.905_11.04.2024-12:31:38.json'),
 PosixPath('/mnt/d/scripts/hil/hil-test-case-gen/results/single_gpt-4o-mini_n-8_acc-0.905_11.04.2024-12:49:27.json')]

In [9]:
def plot_summarize(c, summarize_):
    ax = summarize_["accuracy"].plot.bar(
        title="Accuracy per Sensor",
        xlabel="",
    )

    _ = ax.bar_label(ax.containers[0])

In [10]:
stats = pd.DataFrame()
summarize = pd.DataFrame()

for filename in available_results:
    stats_, summarize_ = analyze(labels, filename, results_path)
    
    stats = pd.concat([stats, stats_])
    summarize = pd.concat([summarize, summarize_])
    

stats.drop(columns="examples", inplace=True)
stats.set_index("number_examples", inplace=True)

summarize.reset_index(drop=True, inplace=True)

In [11]:
stats

,type,model_name,accuracy,number_of_reqs,total_tokens,total_completion_tokens,avg_token_per_req,avg_completion_token_per_req,avg_time_per_req
number_examples,,,,,,,,,
1,single,gpt-4o-mini,0.934307,137,108961,1781,795.335766,13.0,0.931720
3,single,gpt-4o-mini,0.905109,137,188421,1781,1375.335766,13.0,3.557572
5,single,gpt-4o-mini,0.905109,137,264593,1781,1931.335766,13.0,4.004780
8,single,gpt-4o-mini,0.905109,137,381043,1781,2781.335766,13.0,4.469258

In [12]:
summarize

,sensors,type,model_name,number_examples,true,total,false,accuracy,precision,recall,f1
0,Acc,single,gpt-4o-mini,1,23,24,1,0.96,1.00,0.96,0.98
1,Acc & WSA,single,gpt-4o-mini,1,18,18,0,1.00,1.00,1.00,1.00
2,ST,single,gpt-4o-mini,1,27,32,5,0.84,1.00,0.84,0.92
3,WS,single,gpt-4o-mini,1,18,18,0,1.00,1.00,1.00,1.00
4,WSA,single,gpt-4o-mini,1,22,24,2,0.92,1.00,0.92,0.96
5,YR,single,gpt-4o-mini,1,20,21,1,0.95,1.00,0.95,0.98
6,All,single,gpt-4o-mini,1,128,137,9,0.93,0.97,0.93,0.95
7,Acc,single,gpt-4o-mini,3,22,24,2,0.92,1.00,0.92,0.96
8,Acc & WSA,single,gpt-4o-mini,3,18,18,0,1.00,1.00,1.00,1.00
9,ST,single,gpt-4o-mini,3,27,32,5,0.84,1.00,0.84,0.92
10,WS,single,gpt-4o-mini,3,18,18,0,1.00,1.00,1.00,1.00
11,WSA,single,gpt-4o-mini,3,19,24,5,0.79,1.00,0.79,0.88
12,YR,single,gpt-4o-mini,3,20,21,1,0.95,1.00,0.95,0.98
13,All,single,gpt-4o-mini,3,124,137,13,0.91,0.96,0.91,0.93
14,Acc,single,gpt-4o-mini,5,23,24,1,0.96,1.00,0.96,0.98
15,Acc & WSA,single,gpt-4o-mini,5,18,18,0,1.00,1.00,1.00,1.00
16,ST,single,gpt-4o-mini,5,28,32,4,0.88,1.00,0.88,0.93
17,WS,single,gpt-4o-mini,5,18,18,0,1.00,1.00,1.00,1.00
18,WSA,single,gpt-4o-mini,5,16,24,8,0.67,1.00,0.67,0.80
19,YR,single,gpt-4o-mini,5,21,21,0,1.00,1.00,1.00,1.00
20,All,single,gpt-4o-mini,5,124,137,13,0.91,0.93,0.91,0.91
21,Acc,single,gpt-4o-mini,8,23,24,1,0.96,1.00,0.96,0.98
22,Acc & WSA,single,gpt-4o-mini,8,18,18,0,1.00,1.00,1.00,1.00
23,ST,single,gpt-4o-mini,8,28,32,4,0.88,1.00,0.88,0.93
24,WS,single,gpt-4o-mini,8,18,18,0,1.00,1.00,1.00,1.00
25,WSA,single,gpt-4o-mini,8,17,24,7,0.71,1.00,0.71,0.83
26,YR,single,gpt-4o-mini,8,20,21,1,0.95,1.00,0.95,0.98
27,All,single,gpt-4o-mini,8,124,137,13,0.91,0.95,0.91,0.92