In [4]:
import pandas as pd
from pathlib import Path
from testgen.analysis_utils import *

In [5]:
labels = get_sensors_labels()

labels

array(['Acc', 'WSA', 'WS', 'YR', 'ST'], dtype='<U3')

In [6]:
# read results file
base_path = Path().cwd()
results_path = base_path.parent / "results"
    
available_results = get_best_results(results_path, "bulk*.json")

available_results

[PosixPath('/mnt/d/scripts/hil/hil-test-case-gen/results/bulk-2_gpt-4o-mini_n-1_acc-0.89_11.04.2024-13:16:25.json'),
 PosixPath('/mnt/d/scripts/hil/hil-test-case-gen/results/bulk-3_gpt-4o-mini_n-1_acc-0.867_11.04.2024-13:12:14.json'),
 PosixPath('/mnt/d/scripts/hil/hil-test-case-gen/results/bulk-5_gpt-4o-mini_n-1_acc-0.837_11.04.2024-13:14:24.json'),
 PosixPath('/mnt/d/scripts/hil/hil-test-case-gen/results/bulk-8_gpt-4o-mini_n-1_acc-0.824_11.04.2024-13:14:54.json')]

In [7]:
def plot_summarize(summarize_):
    ax = summarize_["accuracy"].plot.bar(
        title="Accuracy per Sensor",
        xlabel="",
    )

    _ = ax.bar_label(ax.containers[0])

In [8]:
stats = pd.DataFrame()
summarize = pd.DataFrame()

for filename in available_results:
    stats_, summarize_ = analyze(labels, filename, results_path)
    
    stats = pd.concat([stats, stats_])
    summarize = pd.concat([summarize, summarize_])
    

stats.drop(columns="examples", inplace=True)
stats.set_index("number_examples", inplace=True)

summarize.reset_index(drop=True, inplace=True)

AttributeError: 'list' object has no attribute 'split'

In [ ]:
stats

,type,type_n,model_name,accuracy,number_of_reqs,total_tokens,total_completion_tokens,avg_token_per_req,avg_completion_token_per_req,avg_time_per_req
number_examples,,,,,,,,,,
1,bulk,3,gpt-4o-mini,0.827957,62,56890,2976,305.860215,16.0,0.354957
1,bulk,5,gpt-4o-mini,0.854054,37,36510,2960,197.351351,16.0,0.155577
1,bulk,8,gpt-4o-mini,0.831522,23,25877,2944,140.635870,16.0,0.162586

In [ ]:
summarize

,sensors,type,type_n,model_name,number_examples,true,total,false,accuracy,precision,recall,f1
0,Acc,bulk,3,gpt-4o-mini,1,30,31,1,0.97,1.00,0.97,0.98
1,Acc & WSA,bulk,3,gpt-4o-mini,1,19,24,5,0.79,1.00,0.79,0.88
2,ST,bulk,3,gpt-4o-mini,1,39,45,6,0.87,1.00,0.87,0.93
3,WS,bulk,3,gpt-4o-mini,1,26,26,0,1.00,1.00,1.00,1.00
4,WSA,bulk,3,gpt-4o-mini,1,14,33,19,0.42,1.00,0.42,0.60
5,YR,bulk,3,gpt-4o-mini,1,26,27,1,0.96,1.00,0.96,0.98
6,All,bulk,3,gpt-4o-mini,1,154,186,32,0.83,0.92,0.83,0.86
7,Acc,bulk,5,gpt-4o-mini,1,27,30,3,0.90,1.00,0.90,0.95
8,Acc & WSA,bulk,5,gpt-4o-mini,1,19,25,6,0.76,1.00,0.76,0.86
9,ST,bulk,5,gpt-4o-mini,1,35,45,10,0.78,1.00,0.78,0.88
10,WS,bulk,5,gpt-4o-mini,1,25,25,0,1.00,1.00,1.00,1.00
11,WSA,bulk,5,gpt-4o-mini,1,26,32,6,0.81,1.00,0.81,0.90
12,YR,bulk,5,gpt-4o-mini,1,26,28,2,0.93,1.00,0.93,0.96
13,All,bulk,5,gpt-4o-mini,1,158,185,27,0.85,0.93,0.85,0.89
14,Acc,bulk,8,gpt-4o-mini,1,29,31,2,0.94,1.00,0.94,0.97
15,Acc & WSA,bulk,8,gpt-4o-mini,1,19,25,6,0.76,1.00,0.76,0.86
16,ST,bulk,8,gpt-4o-mini,1,38,44,6,0.86,1.00,0.86,0.93
17,WS,bulk,8,gpt-4o-mini,1,24,24,0,1.00,1.00,1.00,1.00
18,WSA,bulk,8,gpt-4o-mini,1,17,32,15,0.53,1.00,0.53,0.69
19,YR,bulk,8,gpt-4o-mini,1,26,28,2,0.93,1.00,0.93,0.96
20,All,bulk,8,gpt-4o-mini,1,153,184,31,0.83,0.90,0.83,0.86